### ISSUE TITLE
no license file

### ISSUE THREAD

**Issue by bramvanginneken** [DIAGNijmegen/drive-vessels-unet#1]
This is a public repository, but I do not see a license file. A public repository from DIAGNijmegen like https://github.com/DIAGNijmegen/rse-panimg does have one. Do we have a guideline here? My proposal is that every public repository from DSIAGNijmegen must have a license file. @jmsmkn could you advice what would be a good rule and where we should store this guideline?

**Comment by jmsmkn** [comment]
There are probably too many variables to have a blanket policy, it depends on the stakeholders, funders, maybe even valorisation. 

For this particular repo probably something completely permissive is wanted, so I would use Apache 2.0.

**Comment by kiranvaidhya** [comment]
Apache 2.0 license has been added: c0cd7c057c1767c9f98ddfcb853545ddf46cb4f7
