### ISSUE TITLE
Dockerfile line 20: RUN python -m pip install --user -rrequirements.txt a typo?

### ISSUE THREAD

**Issue by xuagu37** [DIAGNijmegen/drive-vessels-unet#3]
Hi, is this "rrequirements" a typo in line 20 of the Dockerfile?
`RUN python -m pip install --user -rrequirements.txt`

**Comment by kiranvaidhya** [comment]
Not a typo, it's synonymous for `-r requirements`

**Comment by xuagu37** [comment]
Ah sure. I missed the -r flag. Thank you!
